---
# handlers file for installnagios

    - name: Compile nagioscore
      shell: |
        ./configure --with-httpd-conf=/etc/apache2/sites-enabled && make all
      args: 
        chdir: "{{ nagioscorepath }}"

    - name: Create Nagios User and Group
      command: make install-groups-users
      args:
        chdir: "{{ nagioscorepath }}"
      
    - name: Adding www-data user to nagios group
      user:
        name: www-data
        groups: nagios
        append: yes
  
    - name: Install binaries
      command: make install
      args:
        chdir: "{{ nagioscorepath }}"
    
    - name: Install service/daemon
      command: make install-daemoninit
      args:
        chdir: "{{ nagioscorepath }}"

    - name: Install and configure the external command file
      command: make install-commandmode
      args:
        chdir: "{{ nagioscorepath }}"

    - name: Install configuration files for nagios
      command: make install-config
      args:
        chdir: "{{ nagioscorepath }}"
      
    - name: Install  Apache web server configuration files and configures Apache settings
      shell: |
        make install-webconf && a2enmod rewrite && a2enmod cgi
      args:
        chdir: "{{ nagioscorepath }}"

    - name: Create nagiosadmin user
      command: htpasswd -c -b /usr/local/nagios/etc/htpasswd.users nagiosadmin {{ nagiospass }} 

    - name: Restart apache2
      service:
        name: apache2
        enabled: yes
        state: restarted

    - name: Compile nagios plugins
      shell: |
        ./tools/setup && ./configure
      args:
        chdir: "{{ nagiospluginpath }}"

    - name: Install nagiosplugins
      shell: |
        make && make install
      args:
        chdir: "{{ nagiospluginpath }}"

    - name: Restart nagios
      service:
        name: nagios
        state: restarted