- name: Install nagios
  become: yes
  hosts: all
  vars:
    nagioscorepath:   /tmp/nagioscore-nagios-4.4.6
    nagiospluginpath: /tmp/nagios-plugins-release-2.3.3

  tasks:
    - name: Update and install softwares
      apt:
        update_cache: yes
        name: 
          - autoconf
          - gcc  
          - libc6 
          - make 
          - wget 
          - unzip 
          - apache2 
          - php 
          - libapache2-mod-php7.4 
          - libgd-dev
        state: present

    - name: Downloading the Source
      get_url:
        url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        dest: /tmp/
      
    - name: Untar the nagios 
      unarchive:
        remote_src: true
        src: /tmp/nagioscore-nagios-4.4.6.tar.gz
        dest: /tmp/

    - name: Compile
      command: ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      args: 
        chdir: "{{ nagioscorepath }}"

    - name: Making compile
      command: make all
      args: 
        chdir: "{{ nagioscorepath }}"
      
    - name: Create User and Group
      command: make install-groups-users
      args:
        chdir: "{{ nagioscorepath }}"
      
    - name: Adding www-data to nagios
      user:
        name: www-data
        groups: nagios
        append: yes

    - name: Install binaries
      command: make install
      args:
        chdir: "{{ nagioscorepath }}"
    
    - name: Install service/daemonit
      command: make install-daemoninit
      args:
        chdir: "{{ nagioscorepath }}"

    - name: Install commandmode
      command: make install-commandmode
      args:
        chdir: "{{ nagioscorepath }}"

    - name: Install config
      command: make install-config
      args:
        chdir: "{{ nagioscorepath }}"
      
    - name: Install webconf
      command: make install-webconf
      args:
        chdir: "{{ nagioscorepath }}"
    
    - name: a2enmod rewrite
      command: a2enmod rewrite
      args:
        chdir: "{{ nagioscorepath }}"

    - name: a2enmod cgi
      command: a2enmod cgi
      args:
        chdir: "{{ nagioscorepath }} "

    - name: apache user account
      command: htpasswd -b /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin 

    - name: restart apache2
      service:
        name: apache2
        enabled: yes
        state: restarted

    - name: start nagios
      service:
        name: nagios
        state: started

    - name: install softwares
      apt:
        name:
          - autoconf
          - gcc
          - libc6
          - libmcrypt-dev
          - make
          - libssl-dev
          - wget
          - bc
          - gawk
          - dc
          - build-essential
          - snmp
          - libnet-snmp-perl
          - gettext
      tags:
        - v1
      
    - name: Downloading the Source
      get_url:
        url: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
        dest: /tmp/
      tags:
        - v2

    - name: Untar the nagios 
      unarchive:
        remote_src: true
        src: /tmp/nagios-plugins-release-2.3.3.tar.gz
        dest: /tmp/
      tags:
        - v3

    - name: tools setup
      command: ./tools/setup
      args:
        chdir: "{{ nagiospluginpath }}"
    
    - name: tools setup
      command: ./configure
      args:
        chdir: "{{ nagiospluginpath }}"
  
    - name: tools setup
      command: make
      args:
        chdir: "{{ nagiospluginpath }}"
    
    - name: tools setup
      command: make install
      args:
        chdir: "{{ nagiospluginpath }}"

    - name: restarting
      service:
        name: nagios
        state: restarted




    



