- name: Install nagios
  become: yes
  hosts: all

  tasks:
    - name: Update and install softwares
      apt:
        update_cache: yes
        name: 
          - autoconf
          - gcc  
          - libc6 
          - make 
          - wget 
          - unzip 
          - apache2 
          - php 
          - libapache2-mod-php7.4 
          - libgd-dev
        state: present

      - name: Downloading the Source
        get_url:
          url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
          dest: /tmp/