- name: Install nagios
  become: yes
  hosts: all

  tasks:
    - name: Update and install softwares
      apt:
        update_cache: yes
        name: 
          - autoconf
          - gcc  
          - libc6 
          - make 
          - wget 
          - unzip 
          - apache2 
          - php 
          - libapache2-mod-php7.4 
          - libgd-dev
        state: present

    - name: Downloading the Source
      get_url:
        url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        dest: /tmp/
      
    - name: Untar the nagios 
      unarchive:
        remote_src: true
        src: /tmp/nagioscore-nagios-4.4.6.tar.gz
        dest: /tmp/

    - name: Compile
      command: ./configure --with-httpd-conf=/etc/apache2/sites-enable
      args: 
        chdir: /tmp/nagioscore-nagios-4.4.6

    - name: Making compile
      command: make all
      args: 
        chdir: /tmp/nagioscore-nagios-4.4.6
      
    - name: Create User and Group
      command: make install-groups-users
      args:
        chdir: /tmp/nagioscore-nagios-4.4.6
      
    - name: Adding www-data to nagios
      user:
        name: www-data
        groups: nagios
        append: yes

    - name: Install binaries
      command: 
        - make install
        - make install-daemoninit
        - make install-commandmode
        - make make install-config
      args:
        chdir: /tmp/nagioscore-nagios-4.4.6



    



